### PR TITLE
updated all packages to latest

### PR DESCRIPTION
**Pull request by vision10**

### CODE REVIEW

**Comment by mlent** [comment]
Hey friends - wanted to let you know, making this major version upgrade broke our build.

It would be better if something like this were in a major version release, so that it didn't get silently pulled in via subdependencies. As in the latest version of Axios they also changed the import structure.

For anyone else who happens to discover this today, what I've tried so far:

- In package.json, using Yarn's selective dependencies to pin `soap/axios-ntlm` to `1.3.0` which didn't work

No dice...

**Comment by vision10** [comment]
axios-ntlm uses
import axios, { AxiosError, AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

axios docs latest
import axios, {isCancel, AxiosError} from 'axios';

It seems the same, what changed in axios import structure ?

**Comment by mlent** [comment]
@vision10 I'm guessing it's this: https://github.com/axios/axios/releases/tag/v1.2.0

> changed: refactored module exports https://github.com/axios/axios/pull/5162
> change: re-added support for loading Axios with require('axios').default https://github.com/axios/axios/pull/5225

**Comment by louislam** [comment]
I am still using "axios": "~0.27.0", after update axios-ntlm to 1.3.1, it throws such error.

Here is the full error log for your reference:
https://github.com/louislam/uptime-kuma/actions/runs/3542675989/jobs/5954006102

```
  /home/runner/work/uptime-kuma/uptime-kuma/node_modules/axios-ntlm/node_modules/axios/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import axios from './lib/axios.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      15 | const postgresConParse = require("pg-connection-string").parse;
      16 | const mysql = require("mysql2");
    > 17 | const { NtlmClient } = require("axios-ntlm");
```


Since the error throws from `/node_modules/axios-ntlm/node_modules/axios` which is a sub-depdenency. Which also means there are two axios in my project. 

Since axios-ntlm is somehow like a plugin of axios, having a sub-depdenency may not be a good idea.

I would suggest that using peerDependencies to prevent the sub-depdenency issue.

For more details, please read:
https://nodejs.org/es/blog/npm/peer-dependencies/

**Comment by vision10** [comment]
would updating the package to version 1.4.0 solv the problem?

**Comment by mlent** [comment]
@vision10 version 1.4.0 of what? you mean making another release of this package which reverts the change?

**Comment by Loksly** [comment]
same problem, also related to axios and soap, like https://github.com/Catbuttes/axios-ntlm/issues/14

**Pull request merged**
